USE [master]
GO
/****** Object:  Database [chat_18127006]    Script Date: 1/6/2021 9:17:33 AM ******/
CREATE DATABASE [chat_18127006]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'chat_18127006', FILENAME = N'F:\_Source\_CSDL\_DATA\chat_18127006.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'chat_18127006_log', FILENAME = N'F:\_Source\_CSDL\_DATA\chat_18127006_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [chat_18127006] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [chat_18127006].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [chat_18127006] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [chat_18127006] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [chat_18127006] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [chat_18127006] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [chat_18127006] SET ARITHABORT OFF 
GO
ALTER DATABASE [chat_18127006] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [chat_18127006] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [chat_18127006] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [chat_18127006] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [chat_18127006] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [chat_18127006] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [chat_18127006] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [chat_18127006] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [chat_18127006] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [chat_18127006] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [chat_18127006] SET  DISABLE_BROKER 
GO
ALTER DATABASE [chat_18127006] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [chat_18127006] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [chat_18127006] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [chat_18127006] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [chat_18127006] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [chat_18127006] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [chat_18127006] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [chat_18127006] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [chat_18127006] SET  MULTI_USER 
GO
ALTER DATABASE [chat_18127006] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [chat_18127006] SET DB_CHAINING OFF 
GO
ALTER DATABASE [chat_18127006] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [chat_18127006] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [chat_18127006]
GO
/****** Object:  Table [dbo].[files]    Script Date: 1/6/2021 9:17:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[files](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[filename] [nchar](256) NOT NULL,
	[groupname] [nchar](100) NULL,
 CONSTRAINT [PK_files] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[groups]    Script Date: 1/6/2021 9:17:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[groups](
	[name] [nchar](100) NOT NULL,
 CONSTRAINT [PK_groups] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[user_groups]    Script Date: 1/6/2021 9:17:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_groups](
	[username] [nchar](100) NOT NULL,
	[groupname] [nchar](100) NOT NULL,
 CONSTRAINT [PK_user_groups] PRIMARY KEY CLUSTERED 
(
	[username] ASC,
	[groupname] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[users]    Script Date: 1/6/2021 9:17:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[usename] [nchar](100) NOT NULL,
	[password] [nchar](20) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[usename] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[files]  WITH CHECK ADD  CONSTRAINT [FK_files_groupname_TO_groups_name] FOREIGN KEY([groupname])
REFERENCES [dbo].[groups] ([name])
GO
ALTER TABLE [dbo].[files] CHECK CONSTRAINT [FK_files_groupname_TO_groups_name]
GO
ALTER TABLE [dbo].[user_groups]  WITH CHECK ADD  CONSTRAINT [FK_usergroups_groupname_TO_groups_name] FOREIGN KEY([groupname])
REFERENCES [dbo].[groups] ([name])
GO
ALTER TABLE [dbo].[user_groups] CHECK CONSTRAINT [FK_usergroups_groupname_TO_groups_name]
GO
ALTER TABLE [dbo].[user_groups]  WITH CHECK ADD  CONSTRAINT [FK_usergroups_username_TO_users_username] FOREIGN KEY([username])
REFERENCES [dbo].[users] ([usename])
GO
ALTER TABLE [dbo].[user_groups] CHECK CONSTRAINT [FK_usergroups_username_TO_users_username]
GO
USE [master]
GO
ALTER DATABASE [chat_18127006] SET  READ_WRITE 
GO
